name: test
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
jobs:
  conftest:
    runs-on: ubuntu-latest
    steps:
      - name: fail
        run: "false"
      - uses: aquaproj/aqua-installer@v1.0.0
        with:
          aqua_version: v1.1.0
